### ISSUE TITLE
Exception: The given key 'launchConfig' was not present in the dictionary

### ISSUE THREAD

**Issue by yss14** [ThiagoBarradas/rancher-upgrader#1]
### Status

Error / Question

### Steps

Execute `rancher-upgrade` like 

```bash
docker run thiagobarradas/rancher-upgrader execute upgrade --url=https://<url>/v3/project/<project>/workloads/deployment:<namespace>:<deployment> --user=<user> --pass=<secret> --force --wait
```

### Expected behaviour

Upgrading my deployment on rancher.

### Actual behaviour

```
##############################
#      RANCHER UPGRADER!     #
##############################
Ooops! Exception: The given key 'launchConfig' was not present in the dictionary.
```

### Environment

* Docker version 19.03.4, build 9013bf5
* rancher-upgrade:latest
* rancher v2.3.3
* kubernetes v1.16.3

Am I missing something?

**Comment by ThiagoBarradas** [comment]
Sorry abou delay!

This container only works with rancher 1.6.

Soon I will include compatibility with the rancher 2.X.
